"""Tests for commit filtering."""

from __future__ import annotations

from bgkit.data.commit_filters import is_autogenerated, is_trivial_commit


def test_trivial_commit_detection():
    assert is_trivial_commit("bump version to 1.2.3", 5)
    assert is_trivial_commit("fix typo in README", 2)
    assert not is_trivial_commit("Add authentication module", 50)


def test_autogenerated_detection():
    assert is_autogenerated(["package-lock.json"])
    assert is_autogenerated(["yarn.lock", "package-lock.json"])
    assert not is_autogenerated(["src/main.py", "package-lock.json"])
    assert not is_autogenerated(["src/auth.py"])
