#!/usr/bin/env bash
# RULER long-context scout: niah_single_1 + qa_1 at 64K / 128K for stock
# Qwen3.5-0.8B (native context 262144) — hunting the length where the stock
# model's flat-100 grid finally degrades (plan §2026-08-24: at ≤32K it is
# length-flat, so the "long context rescued" RULER story needs the cliff).
# Data generated by the scout prep (data/L65536, data/L131072).
# Refuses to run alongside any phase2-kb GPU container.
#   setsid nohup scripts/run_ruler_scout.sh > /home/werg/bgkit-ckpt-fast/ruler_scout.log 2>&1 &
set -uo pipefail
cd "$(dirname "$0")/.."
set -a; source .env; set +a
FAST=/home/werg/bgkit-ckpt-fast
NVME=/home/werg/bgkit-data-nvme/capability_packaging
COMPOSE="docker compose --env-file .env -f docker/docker-compose.yaml"
log() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*"; }

if ! docker image inspect vllm-node:latest >/dev/null 2>&1; then
  log "vllm-node:latest missing"; exit 1
fi
if [ -n "$(docker ps -q --filter name=phase2-kb)" ] || [ -n "$(docker ps -q --filter name=blob-sft)" ]; then
  log "a GPU training container is running — refusing to start vLLM alongside it"; exit 1
fi

RULER=$NVME/benchmarks/ruler
PRED=$RULER/pred_qwen35_0p8b
for L in 65536 131072; do for T in niah_single_1 qa_1; do
  [ -f "$RULER/data/L$L/$T/validation.jsonl" ] || { log "missing data L$L/$T — run the scout prep first"; exit 1; }
done; done

# 140K max_model_len for the 128K prompts; KV for one 131K sequence on the
# 0.8B is small, but give the server a bit more pool than the 32K runs.
log "starting vllm-fast (max-model-len 140000)"
VLLM_MAX_MODEL_LEN_FAST=140000 VLLM_GPU_UTIL_FAST=0.25 $COMPOSE up -d vllm-fast
healthy=0
for _ in $(seq 1 90); do
  if curl -sf "http://localhost:${VLLM_PORT_FAST:-8091}/v1/models" >/dev/null 2>&1; then healthy=1; break; fi
  sleep 10
done
if [ "$healthy" = "1" ]; then
  log "predicting scout cells (only L65536/L131072 have unpredicted data)"
  /home/werg/bgkit/.venv/bin/python scripts/baseline_ruler_predict.py \
    --data-root "$RULER/data" --out-root "$PRED" \
    --model Qwen/Qwen3.5-0.8B \
    --base-url "http://localhost:${VLLM_PORT_FAST:-8091}/v1" \
    >> "$FAST/baselines_ruler_predict.log" 2>&1
  log "predict rc=$?"
  /home/werg/bgkit/.venv/bin/python scripts/score_ruler.py --pred-root "$PRED"
  log "score rc=$?"
else
  log "vllm-fast did not become healthy — check $COMPOSE logs vllm-fast"
fi
$COMPOSE stop vllm-fast >/dev/null 2>&1 || true
$COMPOSE rm -f vllm-fast >/dev/null 2>&1 || true
log "RULER SCOUT DONE"
