"""Commit filter rules.

Excludes: merge commits, trivial formatting-only changes, auto-generated
code, and very large commits. Preferentially samples commits requiring
cross-file information.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class CommitFilterConfig:
    """Configuration for commit filtering."""

    exclude_merges: bool = True
    max_files_changed: int = 50
    max_diff_lines: int = 5000
    min_diff_lines: int = 3
    exclude_patterns: list[str] | None = None  # e.g., ["*.lock", "*.generated.*"]
    prefer_cross_file: bool = True


def is_trivial_commit(message: str, diff_lines: int) -> bool:
    """Check if a commit is trivial (formatting-only, version bump, etc.)."""
    trivial_prefixes = [
        "bump version",
        "update changelog",
        "format code",
        "fix typo",
        "fix whitespace",
    ]
    msg_lower = message.lower().strip()
    return any(msg_lower.startswith(p) for p in trivial_prefixes) or diff_lines < 3


def is_autogenerated(paths: list[str]) -> bool:
    """Check if a commit touches only auto-generated files."""
    autogen_patterns = [
        "package-lock.json",
        "yarn.lock",
        "go.sum",
        "Cargo.lock",
        ".generated.",
        "__generated__",
    ]
    return all(any(p in path for p in autogen_patterns) for path in paths)
