"""Commit extraction with filtering.

Extracts commits from git repos and applies filtering rules to produce
clean training data. Each commit becomes a potential training example.
"""

from __future__ import annotations

from dataclasses import dataclass

import pygit2

from bgkit.data.commit_filters import CommitFilterConfig, is_autogenerated, is_trivial_commit


@dataclass
class ExtractedCommit:
    """A filtered commit ready for task construction."""

    repo_path: str
    sha: str
    parent_sha: str
    message: str
    diff_paths: list[str]
    diff_hunks: list[list[str]]  # per-file lists of hunks, parallel with diff_paths
    author: str
    timestamp: int
    additions: int = 0
    deletions: int = 0
    is_cross_file: bool = False


def _get_diff_paths_and_hunks(
    repo: pygit2.Repository,
    commit: pygit2.Commit,
    parent: pygit2.Commit | None,
) -> tuple[list[str], list[list[str]], int, int]:
    """Get changed file paths and diff hunks between a commit and its parent.

    Returns:
        (diff_paths, diff_hunks, additions, deletions)
        diff_hunks is a list parallel with diff_paths; each element is a list
        of hunk strings for that file.
    """
    diff = repo.diff(parent, commit) if parent is not None else commit.tree.diff_to_tree()

    diff.find_similar()  # detect renames

    paths = []
    hunks = []
    additions = 0
    deletions = 0

    for patch in diff:
        path = patch.delta.new_file.path
        paths.append(path)
        additions += patch.line_stats[1]
        deletions += patch.line_stats[2]

        file_hunks = []
        for hunk in patch.hunks:
            hunk_lines = [f"{line.origin}{line.content}" for line in hunk.lines]
            file_hunks.append("".join(hunk_lines))
        hunks.append(file_hunks)

    return paths, hunks, additions, deletions


def extract_commits(
    repo_path: str,
    max_commits: int | None = None,
    max_walked_commits: int | None = None,
    config: CommitFilterConfig | None = None,
) -> list[ExtractedCommit]:
    """Extract and filter commits from a git repo.

    Args:
        repo_path: Path to the git repo.
        max_commits: Maximum number of commits to extract.
        max_walked_commits: Maximum number of commits to inspect before
            stopping, including commits rejected by filters.
        config: Filter configuration. Uses defaults if None.

    Returns:
        List of filtered commits (newest first).
    """
    if config is None:
        config = CommitFilterConfig()

    repo = pygit2.Repository(repo_path)

    try:
        head_oid = repo.head.target
    except pygit2.GitError:
        return []

    results = []
    count = 0
    walked = 0

    for commit in repo.walk(head_oid, pygit2.GIT_SORT_TOPOLOGICAL):
        walked += 1
        if max_walked_commits is not None and walked > max_walked_commits:
            break

        # Skip merges
        if config.exclude_merges and len(commit.parents) > 1:
            continue

        parent = commit.parents[0] if commit.parents else None

        # Get diff info
        try:
            diff_paths, diff_hunks, additions, deletions = _get_diff_paths_and_hunks(
                repo, commit, parent
            )
        except (pygit2.GitError, ValueError):
            continue

        # Filter: too many files changed
        if len(diff_paths) > config.max_files_changed:
            continue

        # Filter: diff size
        total_diff_lines = additions + deletions
        if total_diff_lines > config.max_diff_lines:
            continue
        if total_diff_lines < config.min_diff_lines:
            continue

        message = commit.message.strip()

        # Filter: trivial commits
        if is_trivial_commit(message, total_diff_lines):
            continue

        # Filter: autogenerated files only
        if is_autogenerated(diff_paths):
            continue

        # Filter: exclude patterns
        if config.exclude_patterns:
            import fnmatch
            if all(
                any(fnmatch.fnmatch(p, pat) for pat in config.exclude_patterns)
                for p in diff_paths
            ):
                continue

        is_cross_file = len(diff_paths) > 1

        results.append(ExtractedCommit(
            repo_path=repo_path,
            sha=str(commit.id),
            parent_sha=str(parent.id) if parent else "",
            message=message,
            diff_paths=diff_paths,
            diff_hunks=diff_hunks,
            author=commit.author.name,
            timestamp=commit.commit_time,
            additions=additions,
            deletions=deletions,
            is_cross_file=is_cross_file,
        ))

        count += 1
        if max_commits is not None and count >= max_commits:
            break

    return results
